### ISSUE TITLE
Permutation

### ISSUE THREAD

**Issue by GettyScience** [fogellab/multiWGCNA#13]
Hi, 

Just a quick question since you know your code the best, what do you recommend as the minimum value for the number of permutations to run when using multiWGCNA code and still get reasonably accurate results? I have tended to stick around 1000, but this makes processing much longer. Do you think I could work with less or stick with what I have?

Thank you,

**Comment by dariotommasini** [comment]
Hi @GettyScience ,

For which analysis, the PreservationComparisons analysis or the PreservationPermutationTest? The PreservationComparisons analysis just runs WGCNA's native module preservation function which is probably fine with 100 permutations, in my hands. Results are largely identical when you run at least 100 permutations. For the PreservationPermutationTest, I would say as many as possible. With that said, it's incredibly slow so I would try 100 first and see how that goes. We did 2000 permutations in the paper but it ran for several days on the cluster.

**Comment by GettyScience** [comment]
Thank you.

**Comment by klai001** [comment]
For some reason permutation preservation has some error possibly attributing to getPreservation() function. 
When i run getPreservation()
`getPreservation(networks$combined,networks$MT,nPermutations=1,write=FALSE)`
this gives
```
Error in datout[[perm]][[1]]$netPresent: $ operator is invalid for atomic vectors
Traceback:

1. getPreservation(networks$combined, networks$MT, nPermutations = 1, 
 .     write = FALSE)
2. system.time({
 .     mp2 = modulePreservation(multiExpr2, modLabels2, referenceNetworks = 1, 
 .         nPermutations = nPermutations, randomSeed = 1, quickCor = 0, 
 .         verbose = 3, parallelCalculation = TRUE, savePermutedStatistics = FALSE)
 . })   # at line 25-37 of file <text>
3. modulePreservation(multiExpr2, modLabels2, referenceNetworks = 1, 
 .     nPermutations = nPermutations, randomSeed = 1, quickCor = 0, 
 .     verbose = 3, parallelCalculation = TRUE, savePermutedStatistics = FALSE)   # at line 26-36 of file <text>
Timing stopped at: 25.26 15.93 7.224
```

Which basically is the same error when i run PreservationPermutationTest()
results$permutation.test = PreservationPermutationTest(networks$combined@datExpr[sample(12000,3000),], 
                                                       sampleTable, 
                                                       constructNetworksIn = "MT", 
                                                       testPreservationIn = "WT", 
                                                       nPermutations = 1, 
                                                       nPresPermutations = 1, 
                                                       
                                                       # WGCNA parameters for re-sampled networks (should be the same as used for network construction)
                                                       networkType = "signed", TOMType = "unsigned", 
                                                       power = 7, minModuleSize = 50, maxBlockSize = 25000,
                                                       reassignThreshold = 0, minKMEtoStay = 0, mergeCutHeight = 0,
                                                       numericLabels = TRUE, pamRespectsDendro = FALSE, 
                                                       deepSplit = 4, verbose = 3
                                                       )
`Error in datout[[perm]][[1]]$netPresent: $ operator is invalid for atomic vectors
Traceback:`

somehow i suspect theres some dissonance between WGCNA's ModulePreservation() output and your getPreservation()
but i havent manage to debug this so far.
im only running 1 permutation to test/debug the code.


heres a QC on how my DatExpr looks.
blue represents sample names which i had to blank out
![image](https://github.com/fogellab/multiWGCNA/assets/55043905/1c900837-bc9f-4e56-8cf9-0e57d147a32a)

**Comment by dariotommasini** [comment]
You're welcome!
