### ISSUE TITLE
Preservation Error

### ISSUE THREAD

**Issue by GettyScience** [fogellab/multiWGCNA#16]
Hello, I have begun running into this error "Error in eval(expr, p) : object 'name2' not found while running the preservationComparisons function. It happened after I reopened R and uploaded a data save file. 

Thank you,

**Comment by dariotommasini** [comment]
Hi @GettyScience 

Not much I can do based on this info. Can you make a reproducible example using the data provided in the package?

**Comment by GettyScience** [comment]
When I run the below function, with my own data, I get the above error message. It runs for a while and then stops. I was successfully able to run this function before and have not changed any part of my dataset. The only change that occurred was that R died when my laptop died and when I reloaded the session, it was unable to run this function. All other functions appear to be working. I could try to run from a previous version of multiWGCNA and see if the problem is still there? 

results$preservation=iterate(autism_networks[conditions1], # this does autism vs control; change to "conditions2" to perform comparison between FC and TC
                             preservationComparisons, 
                             write=TRUE, 
                             plot=TRUE, 
                             nPermutations=10)

**Comment by GettyScience** [comment]
Hello, 

I just wanted to let you know that the problem appears to me to be that the function getPreservation() is missing a formula for how to name "name2" and so when the file it produces calls for this "name2" it doesn't exist. 

Thank you,

**Comment by dariotommasini** [comment]
Okay I'll look into this. Does this occur when using the example data as well? I'm pretty sure this function was working for others recently. Maybe update to the development version?
