### ISSUE TITLE
Permutation preservation and get preservation error

### ISSUE THREAD

**Issue by klai001** [fogellab/multiWGCNA#17]
For some reason permutation preservation has some error possibly attributing to getPreservation() function.
When i run getPreservation()
`getPreservation(networks$combined,networks$MT,nPermutations=1,write=FALSE)`
this gives

```
Error in datout[[perm]][[1]]$netPresent: $ operator is invalid for atomic vectors
Traceback:

1. getPreservation(networks$combined, networks$MT, nPermutations = 1, 
 .     write = FALSE)
2. system.time({
 .     mp2 = modulePreservation(multiExpr2, modLabels2, referenceNetworks = 1, 
 .         nPermutations = nPermutations, randomSeed = 1, quickCor = 0, 
 .         verbose = 3, parallelCalculation = TRUE, savePermutedStatistics = FALSE)
 . })   # at line 25-37 of file <text>
3. modulePreservation(multiExpr2, modLabels2, referenceNetworks = 1, 
 .     nPermutations = nPermutations, randomSeed = 1, quickCor = 0, 
 .     verbose = 3, parallelCalculation = TRUE, savePermutedStatistics = FALSE)   # at line 26-36 of file <text>
Timing stopped at: 25.26 15.93 7.224
```
Which basically is the same error when i run PreservationPermutationTest()
```
results$permutation.test = PreservationPermutationTest(networks$combined@datExpr[sample(12000,3000),],
sampleTable,
constructNetworksIn = "MT",
testPreservationIn = "WT",
nPermutations = 1,
nPresPermutations = 1,

                                                   # WGCNA parameters for re-sampled networks (should be the same as used for network construction)
                                                   networkType = "signed", TOMType = "unsigned", 
                                                   power = 7, minModuleSize = 50, maxBlockSize = 25000,
                                                   reassignThreshold = 0, minKMEtoStay = 0, mergeCutHeight = 0,
                                                   numericLabels = TRUE, pamRespectsDendro = FALSE, 
                                                   deepSplit = 4, verbose = 3
                                                   )
Error in datout[[perm]][[1]]$netPresent: $ operator is invalid for atomic vectors Traceback:

```
somehow i suspect theres some dissonance between WGCNA's ModulePreservation() output and your getPreservation()
but i havent manage to debug this so far.
im only running 1 permutation to test/debug the code.

heres a QC on how my DatExpr looks.
blue represents sample names which i had to blank out
![image](https://github.com/fogellab/multiWGCNA/assets/55043905/4b7cee86-7a19-4f3d-8ae8-549148f53f1d)

The error doesnt seem to be instant as well i.e. it runs for a few minutes with the verbose flagging genes bla bla bla then dies halfway

**Comment by klai001** [comment]
ive changed to 2 permutations without multithreading- and this gives error`Error in results$permutation.test = PreservationPermutationTest(networks$combined@datExpr[sample(12000, : object of type 'closure' is not subsettable
Traceback:`

its not clear to me why the error message was different from yesterday with the same code apart from perm. this by itself `networks$combined@datExpr[sample(12000,3000),] `  was subsettable

**Comment by dariotommasini** [comment]
Hi @klai001 

Are you trying with your own data or the vignette data? This function worked last I checked a couple weeks ago, so if it works for you with the vignette data then this is likely a formatting issue. Might also be a version thing. Are you using the latest version?

**Comment by klai001** [comment]
I downloaded the package (through Bioconductor)  with the same versions of BioConductor and R as the vignette; I realised though, that the PresP function can't be called through the multiWGCNA package- therefore I used the source codes here in this GitHub repo; if those are the latest, I believe then it's the latest 

Haven't checked with the example dataset as yet

**Comment by dariotommasini** [comment]
Oh sorry, I thought you were calling the preservationComparisons function for the module preservation. The preservationpermutationtest function is rather new indeed and not well tested. I'll look into this and get back to you. 

Have you checked if the astrocyte vignette code works on your machine?

**Comment by klai001** [comment]
Yes, the vignette runs fine  (and so is my data if I follow the vignette to a T)

**Comment by dariotommasini** [comment]
Great!
