### ISSUE TITLE
Error on constructNetworks on RNA-Seq data - unique rownames

### ISSUE THREAD

**Issue by shasabhi1** [fogellab/multiWGCNA#18]
Hello,

I have tried using multiWGCNA to analyze RNA-Seq data across two strains and two tissue types. I have rownames that correspond to ENSEMBL IDs but I'm getting the error:
error in `.rownamesdf<-`(x, value = value) : duplicate 'row.names' are not allowed.

I have checked that each row has a unique ID by using the function rownames(df) = make.names(rownames(df), unique = TRUE), and have separately added unique numbers to each ID to 'tag' it.

Please advise on why this might be happening if possible!

<img width="889" alt="Capture231123" src="https://github.com/fogellab/multiWGCNA/assets/140649679/a45175bc-0609-4767-8cb8-9a0f39678e66">

Best,
Abhishek

**Comment by dariotommasini** [comment]
Hello!

Can you show me where the error occurs? Eg can I see the whole backtrace? 

I suspect that it's the column names that are the issue. WGCNA usually considers the samples as rows so they get transposed at some step. Have you checked that your column names are unique as well?

**Comment by shasabhi1** [comment]
Hello,

I've resolved the issue, I did not format the metadata correctly which lead to that error. I have another question: if I have Diet and Tissue traits and I'm trying to find modules that are found in **both** tissue types that are representative of the high fat diet feeding, would overlap analysis of what common HFD modules are found in HFD_vs_Tissue1 and HFD_vs_Tissue2 work? Ex. if I identify HFD_002 is found significant in Tissue1_001 and Tissue2_002, should I see which genes overlap between these two tissue modules?

**Comment by dariotommasini** [comment]
I think you have it right. You need to identify all the tissue 1 modules that have a significant association to diet. Then you have to find all the tissue 2 modules that have a significant association to diet. Then do the overlap analysis to see if the significant module(s) from tissue 1 overlap with significant modules from tissue 2. 

The constructnetworks function actually already computes these associations for you. So just check that output in WGCNAObject@trait. This reports the Pearson cor test p-values. Then use the overlapComparisons function to calculate the overlap statistics. The plots from overlapcomparisons should be useful as they already label which modules are significant at 0.05 level.

**Comment by shasabhi1** [comment]
Thank you @dariotommasini this makes sense, I appreciate your help!

**Comment by niederhuth** [comment]
> Hello,
> 
> I've resolved the issue, I did not format the metadata correctly which lead to that error. I have another question: if I have Diet and Tissue traits and I'm trying to find modules that are found in **both** tissue types that are representative of the high fat diet feeding, would overlap analysis of what common HFD modules are found in HFD_vs_Tissue1 and HFD_vs_Tissue2 work? Ex. if I identify HFD_002 is found significant in Tissue1_001 and Tissue2_002, should I see which genes overlap between these two tissue modules?

Can you clarify what the issue was? I have been encountering the same issue.
