### ISSUE TITLE
TOMFlowPlot issue in autism demo 

### ISSUE THREAD

**Issue by hannahthomas1235** [fogellab/multiWGCNA#20]
I am just running through the Vignette with the demo data and I am having issues with this section
`networks = c("autism", "controls")
toms = lapply(networks, function(x) {
  load(paste0(x, '-block.1.RData'))
  get("TOM")
  })`

It returns the error:
`Warning: cannot open compressed file 'autism-block.1.RData', probable reason 'No such file or directory'Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection`

I already checked that saveTOMs = TRUE in the constructNetworks function. Any suggestions?

**Comment by dariotommasini** [comment]
Hi @hannahthomas1235 ,

Did you check if it wrote that rds file during network construction? Maybe it called it something else for some reason?

**Comment by hannahthomas1235** [comment]
I don't think that the rds files are being generated at all during network construction. I haven't changed any code, but I am running the latest R.

**Comment by dariotommasini** [comment]
Okay, thank you for the info. Then there seems to be an issue with the constructNetwork function. Are you using saveTOMs = TRUE? Perhaps you don't have write permissions to the directory you're running the vignette in? 

The vignette seems to be compiling properly on bioconductor: https://bioconductor.org/packages/3.20/bioc/vignettes/multiWGCNA/inst/doc/autism_full_workflow.html

**Comment by dariotommasini** [comment]
I would also make sure you have the newest version of the package since that section of the vignette is recent. You can install from development as shown in the vignette.

**Comment by dariotommasini** [comment]
Closing for now, but let me know if it's not resolved I can reopen.
