### ISSUE TITLE
CoexpressionLineGraph

### ISSUE THREAD

**Issue by GettyScience** [fogellab/multiWGCNA#4]
Hello, 

thank you for all of your help over the last few days.

Would you please provide me an example of the Coexpression Line Graph function that produced figure 2d of the Tommasini and Fogel (2023) paper? I am struggling to interpret it from the code alone. 

Thank you,

**Comment by dariotommasini** [comment]
Okay, I can add documentation for that function and add an example to the astrocyte vignette. I'll take care of this within the next couple days.

**Comment by dariotommasini** [comment]
Hi, please try installing the new version, and see the astrocyte vignette. It now includes an example of the coexpression line graph function and reproduces Figure 2D from Tommasini and Fogel.

**Comment by dariotommasini** [comment]
Hi @GettyScience, 

Have you had a chance to try the function and vignette? Is so, could you confirm that it's working for you? I can close the issue if that's the case. Thanks!

**Comment by GettyScience** [comment]
Hi, yes I was able to get it to work! Thank you!

**Comment by smukher2** [comment]
PLEASE HELP STOP PLAGIARISM AND VILLAINOUS SCIENTISTS BRENT FOGEL (UCLA) AND DARIO TOMMASINI (now PhD student in UC Berkeley) BY NOT CITING OR USING THIS, OR THEIR OTHER CODES AND PAPERS BY THEM. INSTEAD USE AND CITE THE ORIGINAL WORKS (WITH VIDEO TUTORIAL) BY DR. STEVE HORVATH, DR. PETER LANGFELDER AND DR. JEREMY MILLER.(details below)

*For details about wrong doings by Brent Fogel including and not limited to plagiarism by Brent Fogel and Dario Tommasini
please see open letter at http://tinyurl.com/bde788x2 or file 'This To Apprise You About Wrong Doings By Brent Fogel including and not limited to plagiarism by Brent Fogel and Dario Tommasini.pdf' posted at https://gitlab.com/smukher2/openletter that I also emailed to UCLA, UC Berkeley, iScience and BMC Bioinformatics reporting plagiarism by Brent Fogel and Dario Tommasini in their two papers using this multiWGCNA code https://github.com/fogellab/multiWGCNA:
Tommasini D, Fox R, Ngo KJ, Hinman JD, Fogel BL. Alterations in oligodendrocyte transcriptional networks reveal region-specific vulnerabilities to neurological disease. iScience. 2023 Mar 8;26(4):106358. doi: 10.1016/j.isci.2023.106358. PMID: 36994077; PMCID: PMC10040735.
Tommasini D, Fogel BL. multiWGCNA: an R package for deep mining gene co-expression networks in multi-trait expression data. BMC Bioinformatics. 2023 Mar 24;24(1):115. doi: 10.1186/s12859-023-05233-z. PMID: 36964502; PMCID: PMC10039544.

*If you need WGCNA codes for different applications with video turorial consider using the original works (with video tutorials) by Dr. Steve Horvath, Dr. Peter Langfelder and Dr. Jeremy Miller:
Langfelder, P., Horvath, S. WGCNA: an R package for weighted correlation network analysis. BMC Bioinformatics 9, 559 (2008). https://doi.org/10.1186/1471-2105-9-559
Miller JA, Horvath S, Geschwind DH. Divergence of human and mouse brain transcriptome highlights Alzheimer disease pathways. Proc Natl Acad Sci U S A. 2010 Jul 13;107(28):12698-703. Epub 2010 Jun 25. PMID: 20616000; PMCID: PMC2906579. https://doi.org/10.1073/pnas.0914257107

Video: Dr. Steve Horvath Weighted gene co-expression network analysis https://youtu.be/rRIRMW_RRS4?si=A-ZivIzwdRVLpaLa
Video: Dr. Jeremy Miller How WGCNA Can be Used to Compare and Contrast Two Networks https://youtu.be/aBD67YmCBK4?si=eW9Ybv2nIWDUjkdT
Full Playlist: WGCNA https://www.youtube.com/playlist?list=PLtlynCnS_vmB2kwhfkcfxIDbsSO9uniM5
Resources: Dr. Peter Langfelder lists further resources on his website https://peterlangfelder.com/2018/11/25/wgcna-resources-on-the-web/

Best regards, 
Shradha Mukherjee
https://gitlab.com/smukher2
https://github.com/smukher2
https://orcid.org/0000-0002-3249-2551
https://pubmed.ncbi.nlm.nih.gov/?term=Shradha+Mukherjee
