### ISSUE TITLE
Error in `palette()`

### ISSUE THREAD

**Issue by zhenqiangfu** [fogellab/multiWGCNA#8]
_Hello, thank you for providing this efficient tool. I encountered a drawing problem during use.
as follows:_

diffModuleExpression(autism_networks[["combined"]], 
                     geneList = topNGenes(autism_networks[["combined"]], "combined_003"), 
                     design = sampleTable,
                     test = "ANOVA",
                     plotTitle = "combined_003",
                     plot = TRUE)
Error in `palette()`:
! Insufficient values in manual scale. 3 needed, but only 2 provided.
Run `rlang::last_trace()` to see where the error occurred.

I look forward to your answer.
Best wishes.

**Comment by dariotommasini** [comment]
Hi @zhenqiangfu , 

I'm having trouble reproducing this. Are you running the autism vignette? Maybe you can try installing from devel and see if the error persists? This is what happens when I do it: 

```
> diffModuleExpression(autism_networks[["combined"]],
+                      geneList = topNGenes(autism_networks[["combined"]], "combined_003"),
+                      design = sampleTable,
+                      test = "ANOVA",
+                      plotTitle = "combined_003",
+                      plot = TRUE)
```
<img width="501" alt="Screenshot 2023-11-24 at 6 32 33 PM" src="https://github.com/fogellab/multiWGCNA/assets/103676484/1b234b37-6dd1-4623-8af3-b39bfea6fe84">

**Comment by zhenqiangfu** [comment]
Thanks for your answer. I guess it is because I set three conditions. I have three tissues.

**Comment by dariotommasini** [comment]
At the moment, multiWGCNA can only handle two conditions, e.g. disease status and tissues. That said, three tissues should be no problem, because that just means the that tissue condition has 3 classes. Your sample table should look like something like this if you had say 4 conditions: 

```
> sampleTable
DataFrame with 36 rows and 3 columns
                Sample     Disease      Region
           <character> <character> <character>
EAE_1            EAE_1         EAE         Cbl
EAE_2            EAE_2         EAE         Cbl
EAE_3            EAE_3         EAE         Cbl
EAE_4            EAE_4         EAE         Cbl
EAE_5            EAE_5         EAE         Cbl
...                ...         ...         ...
healthy_12  healthy_12          WT       Hippo
healthy_13  healthy_13          WT          Sc
healthy_14  healthy_14          WT          Sc
healthy_15  healthy_15          WT          Sc
healthy_16  healthy_16          WT          Sc
```

**Comment by smukher2** [comment]
PLEASE HELP STOP PLAGIARISM AND VILLAINOUS SCIENTISTS BRENT FOGEL (UCLA) AND DARIO TOMMASINI (now PhD student in UC Berkeley) BY NOT CITING OR USING THIS, OR THEIR OTHER CODES AND PAPERS BY THEM. INSTEAD USE AND CITE THE ORIGINAL WORKS (WITH VIDEO TUTORIAL) BY DR. STEVE HORVATH, DR. PETER LANGFELDER AND DR. JEREMY MILLER.(details below)

*For details about wrong doings by Brent Fogel including and not limited to plagiarism by Brent Fogel and Dario Tommasini
please see open letter at http://tinyurl.com/bde788x2 or file 'This To Apprise You About Wrong Doings By Brent Fogel including and not limited to plagiarism by Brent Fogel and Dario Tommasini.pdf' posted at https://gitlab.com/smukher2/openletter that I also emailed to UCLA, UC Berkeley, iScience and BMC Bioinformatics reporting plagiarism by Brent Fogel and Dario Tommasini in their two papers using this multiWGCNA code https://github.com/fogellab/multiWGCNA:
Tommasini D, Fox R, Ngo KJ, Hinman JD, Fogel BL. Alterations in oligodendrocyte transcriptional networks reveal region-specific vulnerabilities to neurological disease. iScience. 2023 Mar 8;26(4):106358. doi: 10.1016/j.isci.2023.106358. PMID: 36994077; PMCID: PMC10040735.
Tommasini D, Fogel BL. multiWGCNA: an R package for deep mining gene co-expression networks in multi-trait expression data. BMC Bioinformatics. 2023 Mar 24;24(1):115. doi: 10.1186/s12859-023-05233-z. PMID: 36964502; PMCID: PMC10039544.

*If you need WGCNA codes for different applications with video turorial consider using the original works (with video tutorials) by Dr. Steve Horvath, Dr. Peter Langfelder and Dr. Jeremy Miller:
Langfelder, P., Horvath, S. WGCNA: an R package for weighted correlation network analysis. BMC Bioinformatics 9, 559 (2008). https://doi.org/10.1186/1471-2105-9-559
Miller JA, Horvath S, Geschwind DH. Divergence of human and mouse brain transcriptome highlights Alzheimer disease pathways. Proc Natl Acad Sci U S A. 2010 Jul 13;107(28):12698-703. Epub 2010 Jun 25. PMID: 20616000; PMCID: PMC2906579. https://doi.org/10.1073/pnas.0914257107

Video: Dr. Steve Horvath Weighted gene co-expression network analysis https://youtu.be/rRIRMW_RRS4?si=A-ZivIzwdRVLpaLa
Video: Dr. Jeremy Miller How WGCNA Can be Used to Compare and Contrast Two Networks https://youtu.be/aBD67YmCBK4?si=eW9Ybv2nIWDUjkdT
Full Playlist: WGCNA https://www.youtube.com/playlist?list=PLtlynCnS_vmB2kwhfkcfxIDbsSO9uniM5
Resources: Dr. Peter Langfelder lists further resources on his website https://peterlangfelder.com/2018/11/25/wgcna-resources-on-the-web/

Best regards, 
Shradha Mukherjee
https://gitlab.com/smukher2
https://github.com/smukher2
https://orcid.org/0000-0002-3249-2551
https://pubmed.ncbi.nlm.nih.gov/?term=Shradha+Mukherjee

**Comment by smukher2deplatformed** [comment]
FogelLab https://fogellab.neurology.ucla.edu/lab-members/ and Tommasini Dario https://www.linkedin.com/in/dario-tommasini plagerised my work http://tinyurl.com/bde788x2 & deplatformed me on GitHub https://gitlab.com/smukher2 LinkedIn https://www.linkedin.com/in/smukher2/

Don't de-platform them like they did to me because we all deerve freedom of speech and right to know, but use your judgement so that their injusice is not repeated. As users and employers fire them, defunding them, not using their work.
